# Generated by Django 5.0.4 on 2024-04-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Attendo_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
